[[map_items]]
year = 2023
period = "Q4"
description = "MoKa Read Shop Opens"

[[map_items]]
year = 2024
period = "Q2"
description = "MoKa Reads Resources Opens"

[[map_items]]
year = 2024
period = "Q1"
description = "Zig Unleashed Releases"

[[map_items]]
year = 2024
period = "Q2"
description = "Exploring Rust Part 1 Starts Initial Production"

[[map_items]]
year = 2024
period = "Q3"
description = "MoKa Template Releases on TexCreate"

[[map_items]]
year = 2025
period = "Q2"
description = "Exploring Rust Part 1 Releases"

[[map_items]]
year = 2025
period = "Q4"
description = "Prepare Exploring Rust Part 2 or Carbon for C++ Programmers (if Carbon comes out 1.0)"

